# Author : Sukhdeep Singh
# Organization : Max Planck
# template for qsub scripts
# Usage : qsub cuffmerge.qsub assemblies.txt
######################################################################

#!/bin/bash
# qsub parameters beginning with #$
# Use bash as the interpreter
#$ -S /bin/bash
#before executing the command thange to the working directory
#$ -cwd
#set your mailaddress
#$ -M sukhdeeps@biotec.tu-dresden.de
# we want a mail on beginning and end of the job 'ADD $ IN START TO ACTIVATE E-EMAIL NOTIFICATION'
# -m be
#submit the complete environment to the execution host
#$ -V
# merge stdout and stderr
#$ -j y
# set your output file
# -o echo.log

# exporting LD Library Path
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/share/apps/lib/

#now we can run our command here.
cuffmerge -g /projects/grub/archive/Mus_musculus/UCSC/mm9/Annotation/Genes/genes.gtf -s /projects/grub/archive/Mus_musculus/UCSC/mm9/Sequence/WholeGenomeFasta/genome.fa -p $NSLOTS $1
