# multithread script for sam2rmdup.sh to run single sample on a	different processor
# Author : Sukhdeep Singh
# Organization : Max Planck
# Usage : qsub task.qsub $1
# Automated Usage : files=(`ls L*.gz`) && size=${#files[@]} ; for ((i=1;i<=size;i++)); do qsub ~/src/qsub/fastxKit.qsub ${files[$i-1]} `sed -n "$i"p adapters.txt` 49 ; done
## Requires all adapters in a text file in a sequential order, or get the 6 alphabet sequence from fastqc report
######################################################################

#!/bin/bash
# qsub parameters beginning with #$
# Use bash as the interpreter
#$ -S /bin/bash
#before executing the command thange to the working directory
#$ -cwd
#set your mailaddress
#$ -M sukhdeeps@biotec.tu-dresden.de
# we want a mail on beginning and end of the job 'ADD $ IN START TO ACTIVATE E-EMAIL NOTIFICATION'
# -m be
#submit the complete environment to the execution host
#$ -V
# merge stdout and stderr
#$ -j y
file=$1
# set your output file
#$ -o $1.txt

#now we can run our command here.
sh ~/src/shell/fastx_collapser.sh $1 $2 $3 > collapsed.log
#fastqc $1 $1.qc.log
