# multithread script for sam2rmdup.sh to run single sample on a	different processor
# Author : Sukhdeep Singh
# Organization : Max Planck
# Usage : qsub task.qsub $1
# Automated Usage : files=(`ls L*.gz`) && size=${#files[@]} ; for ((i=1;i<=size;i++)); do qsub ~/src/qsub/fastxKit.qsub ${files[$i-1]} `sed -n "$i"p adapters.txt` 49 ; done
## Requires all adapters in a text file in a sequential order, or get the 6 alphabet sequence from fastqc report
######################################################################

#!/bin/bash
# qsub parameters beginning with #$
# Use bash as the interpreter
#$ -S /bin/bash
#before executing the command thange to the working directory
#$ -cwd
#set your mailaddress
#$ -M sukhdeeps@biotec.tu-dresden.de
# we want a mail on beginning and end of the job 'ADD $ IN START TO ACTIVATE E-EMAIL NOTIFICATION'
# -m be
#submit the complete environment to the execution host
#$ -V
# merge stdout and stderr
#$ -j y
file=$1
# set your output file
#$ -o subtract_qsub.log

#now we can run our command here.
if [ -z "$1" ]; then
echo "~/src/shell/subtract.sh A.bed B.bed overlapThreshold(in float - optional)"
exit 1
fi

if [ -z "$3" ]; then
echo "Control subtraction with 0.5 overlap threhsold proceeded"
subtractBed -a $1 -b $2 -f 0.5 > $1_subtract.bed
mv $1_subtract.bed .

else
echo "Control subtraction with "$3" overlap threhsold proceeded"
subtractBed -a $1 -b $2 -f $3 > $1_subtract.bed
mv $1_subtract.bed .
fi
