# pBWA script for aligning the raw fastq short read file to the reference genome of mouse (mm9)
# Author : Sukhdeep Singh
# Organization : Max Planck
# Usage : qsub ~/src/useFul/pBWA/pBWA_raw2sam.sh $1 $2 - not being used YET
# $1 = fastqfile, $2= number of cpu
######################################################################

#!/bin/bash
# qsub parameters beginning with #$
# Use bash as the interpreter
#$ -S /bin/bash
#before executing the command thange to the working directory
#$ -cwd
#submit the complete environment to the execution host
#$ -V
# merge stdout and stderr
#$ -j y
file=$1
# set your output file
#$ -o $1.txt

# now initialize the parallel environment with 20 cpus
#$ -pe orte 24

#now we can run our command here.
/opt/openmpi/bin/mpirun -np 24 --mca btl_tcp_if_include eth0 pBWA aln -f $file.sai /biodata/biodb/ABG/genomes/mouse/mm9/mm9 $1
/opt/openmpi/bin/mpirun -np 24 --mca btl_tcp_if_include eth0 pBWA samse -f $file.sam /biodata/biodb/ABG/genomes/mouse/mm9/mm9 $file.sai $1
#cat $file*sam > $file.sam

